# Just template for education purpose
# Fist Steps
# New commet for remote repo
# branching version
# some more branching features
---
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-a4c7edb2
      InstanceType: t2.micro
